title: Benjamin Andersons Engineering Blog
description: Benjamin's portfolio website documenting the different projects he's working on and the lessons he learnt along the way. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "engiebenji.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-first:   BENJAMIN 
author-last:    ANDERSON
author-image:   1.webp
author-job:     ELECTRONIC ENGINEER
author-email:   thebenjaminjanderson@gmail.com
author-twitter: engiebenji1999
about-author:   I'm a graduate electronic engineer interested in hardware design, using this blog website to document my projects.

# Social settings
social-twitter:   engiebenji1999
social-github:    BenjaminJAnderson
social-linkedin:  engiebenji

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: EngieBenji # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
