title: Hello! I'm Benjamin Anderson
description: > # this means to ignore newlines until "baseurl:"   You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Benjamin's portfolio website documenting the different projects he is working on and the lessons he learnt along the way. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "engiebenji.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Benjamin Anderson # add your name
author-img: BezelLogo128128.png # add your photo
about-author: I am a Graduate Electronic Engineer focusing interested in Hardware design. Always hungry to keep learning. # add description
social-twitter: engiebenji1999 # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: BenjaminJAnderson # add your Github handle
social-linkedin: engiebenji # add your Linkedin handle
social-email: thebenjaminjanderson@gmail.com # add your Email address

# Disqus
discus-identifier: disqus_9W6nxPA4Q2 # add your discus identifier (NOT WORKING TRY ENABLING JS AND LOOK AT DISQUS HTML)

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
